config/routes.rb
Rails.application.routes.draw do
  resources :images
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :images
	root to: 'images#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery 
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:image, :pathImage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for @image, :html => {:multipart => true} do |f| %>
<div class="wrapper">
    <div class="file-field input-field">
      <div class="btn">
        <span>Imagen:</span>
	<%= f.file_field :image %>

      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>

</div>

  <p><%= f.submit " Subir Imagen", class: "btn-large waves-effect waves-light", id: "subirIM"  %></p>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>
<br>
<%= link_to 'Ver', @image , class:"btn"%> |
<%= link_to 'Atras', images_path, class:"btn" %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Imagenes</h1>

<table>
  <thead>
    <tr>
      <th>Imagen</th>
      <th>Nombre</th>
	<th>Creada el</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
	      <td><%= image_tag image.image.url, :size => '50x50' %></td>
        <td><%= if image.image.length > 17 then '...'else '' end +image.image.to_s[-17..-1] %></td>
	      <td><%= image.created_at %></td>
        <td><%= link_to 'Ver', image, class:"btn" %></td>
        <td><%= link_to 'Editar', edit_image_path(image) , class:"btn"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Imagen', new_image_path , class: "btn-large waves-effect waves-light"%>
<br>
<p>
</p>

<p>
</p>
<p>
</p>
 &nbsp;&nbsp; 

app/views/images/new.html.erb
<h1>Selecciona la imagen</h1>


<%= render 'form', image: @image %>
<br>
<%= link_to 'atras', images_path, class: "btn-large waves-effect waves-light"  %>
<script>
	$("#image_image").click(function(){
		$("#subirIM").css("display","inline");
	})
</script>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <%= image_tag @image.image.url %>
</p>
 

<p>
  <strong>Creada el: </strong>

 <%= @image.created_at %>
</p>

<%= link_to 'Edit', edit_image_path(@image), class: "btn-large waves-effect waves-light" %> |
<%= link_to 'Back', images_path, class: "btn-large waves-effect waves-light" %>
<p>
</p>
<p>
</p>
 &nbsp;&nbsp; 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImgsApp</title>
    <!-- <%= csrf_meta_tags %> -->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>



<nav>
    <div class="nav-wrapper teal darken-3">

<%= link_to images_path do %> 
	 <i class="material-icons large center" >home</i> 
<%end %>MIERDA
    </div>
  </nav>
  <div class="container">  
    <%= yield %>
  </div>                   
</body>
</html>